/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package examen_lab_1p;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Arena1 extends javax.swing.JFrame {

    /**
     * Creates new form Arena1
     */
    public Arena1() {
        /**
         * Para poner color desde el source tomé como soporte:
         *  https://www.youtube.com/watch?v=-cow14jmuBI
         */
        getContentPane().setBackground(new java.awt.Color(0,99,45));
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        atacar_Brujita = new javax.swing.JButton();
        atacar_Hierro = new javax.swing.JButton();
        var_brujita = new javax.swing.JTextField();
        var_hierro = new javax.swing.JTextField();
        esp_brujita = new javax.swing.JButton();
        esp_hierro = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arena1");
        setForeground(java.awt.Color.white);

        atacar_Brujita.setText("Atacar");
        atacar_Brujita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacar_BrujitaActionPerformed(evt);
            }
        });

        atacar_Hierro.setText("Atacar");
        atacar_Hierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacar_HierroActionPerformed(evt);
            }
        });

        var_brujita.setEditable(false);
        var_brujita.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        var_brujita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var_brujita.setText("500");
        var_brujita.setBorder(new javax.swing.border.MatteBorder(null));
        var_brujita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_brujitaActionPerformed(evt);
            }
        });

        var_hierro.setEditable(false);
        var_hierro.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        var_hierro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var_hierro.setText("350");
        var_hierro.setBorder(new javax.swing.border.MatteBorder(null));
        var_hierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                var_hierroActionPerformed(evt);
            }
        });

        esp_brujita.setText("Recuperar y pasar turno");
        esp_brujita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp_brujitaActionPerformed(evt);
            }
        });

        esp_hierro.setText("Recuperar y pasar turno");
        esp_hierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esp_hierroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(var_brujita, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(atacar_Brujita, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(esp_brujita)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(var_hierro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(atacar_Hierro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp_hierro))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atacar_Brujita)
                    .addComponent(atacar_Hierro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var_hierro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var_brujita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esp_hierro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esp_brujita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atacar_BrujitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atacar_BrujitaActionPerformed
        // TODO add your handling code here:
        int var_bruja = Integer.parseInt(var_hierro.getText());
        var_bruja -= 10 +(Math.random()* 1000)%7;
        var_hierro.setText(""+var_bruja);
        
        if (var_bruja <= 0) {
            msjHierro();
        }
        
        int var_cHierro = Integer.parseInt(var_brujita.getText());
        var_cHierro -= 8 +(Math.random()* 1000)%4;
        var_brujita.setText(""+var_cHierro);
        
        if (var_cHierro <= 0) {
            msjBrujita();
        }
    }//GEN-LAST:event_atacar_BrujitaActionPerformed

    private void atacar_HierroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atacar_HierroActionPerformed
        // TODO add your handling code here:
        int var_cHierro = Integer.parseInt(var_brujita.getText());
        var_cHierro -= 8 +(Math.random()* 1000)%4;
        var_brujita.setText(""+var_cHierro);
        
        if (var_cHierro <= 0) {
            msjBrujita();
        }
        
        int var_bruja = Integer.parseInt(var_hierro.getText());
        var_bruja -= 10 +(Math.random()* 1000)%7;
        var_hierro.setText(""+var_bruja);
        
        if (var_bruja <= 0) {
            msjHierro();
        }
    }//GEN-LAST:event_atacar_HierroActionPerformed

    private void esp_brujitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp_brujitaActionPerformed
        // TODO add your handling code here:
        var_hierro.setText(""+(var_hierro.getText()+100));
    }//GEN-LAST:event_esp_brujitaActionPerformed

    private void esp_hierroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp_hierroActionPerformed
        // TODO add your handling code here:
        var_brujita.setText(""+(var_brujita.getText()+100));
    }//GEN-LAST:event_esp_hierroActionPerformed

    private void var_hierroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_hierroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var_hierroActionPerformed

    private void var_brujitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_var_brujitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_var_brujitaActionPerformed
    
    //funciones para mostrar los mensajes de quien perdió...
    public void msjHierro(){
        JOptionPane.showMessageDialog(var_hierro, "Caballero de Hierro Perdió...");
        dispose();
        Menu abrir = new Menu();
        abrir.setVisible(true);
    }
    
    public void msjBrujita(){
        JOptionPane.showMessageDialog(var_brujita,"Brujita Perdió...");
        dispose();
        Menu abrir = new Menu();
        abrir.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arena1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arena1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arena1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arena1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arena1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atacar_Brujita;
    private javax.swing.JButton atacar_Hierro;
    private javax.swing.JButton esp_brujita;
    private javax.swing.JButton esp_hierro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField var_brujita;
    private javax.swing.JTextField var_hierro;
    // End of variables declaration//GEN-END:variables
}
