/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EXAMEN;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ArenaFuego extends javax.swing.JFrame {

    /**
     * Creates new form Arena1
     */
    public ArenaFuego() {
        getContentPane().setBackground(new java.awt.Color(0,96,46));
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        Atak_EqFuego = new javax.swing.JButton();
        atacar_Hierro = new javax.swing.JButton();
        var_eqF = new javax.swing.JTextField();
        var_visita = new javax.swing.JTextField();
        esp_brujita = new javax.swing.JButton();
        esp_hierro = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Arena1");
        setForeground(java.awt.Color.white);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen_lab_1p/Campo1.png"))); // NOI18N

        Atak_EqFuego.setText("Atacar");
        Atak_EqFuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacar_EquipoFuego(evt);
            }
        });

        atacar_Hierro.setText("Atacar");
        atacar_Hierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atacar_EquipoVisitante(evt);
            }
        });

        var_eqF.setEditable(false);
        var_eqF.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        var_eqF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var_eqF.setText("500");
        var_eqF.setBorder(new javax.swing.border.MatteBorder(null));

        var_visita.setEditable(false);
        var_visita.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        var_visita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        var_visita.setText("350");
        var_visita.setBorder(new javax.swing.border.MatteBorder(null));

        esp_brujita.setText("Recuperar y pasar turno");
        esp_brujita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperarEqFuego(evt);
            }
        });

        esp_hierro.setText("Recuperar y pasar turno");
        esp_hierro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperarEqVisitante(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(var_eqF, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(var_visita, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Atak_EqFuego, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp_brujita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atacar_Hierro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(esp_hierro))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atak_EqFuego)
                    .addComponent(atacar_Hierro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var_visita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(var_eqF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esp_hierro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(esp_brujita, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atacar_EquipoFuego(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int var_bruja = Integer.parseInt(var_visita.getText());
        var_bruja -= 10 +(Math.random()* 1600)%12;
        var_visita.setText(""+var_bruja);
        
        if (var_bruja <= 0) {
            msjEquipoHielo();
        }
        

    }

    private void atacar_EquipoVisitante(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atacar_HierroActionPerformed
        // TODO add your handling code here:
        int var_cHierro = Integer.parseInt(var_eqF.getText());
        var_cHierro -= 8 +(Math.random()* 1600)%12;
        var_eqF.setText(""+var_cHierro);
        
        if (var_cHierro <= 0) {
            msjEquipoFuego();
        }
        
    }

    private void RecuperarEqFuego(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp_brujitaActionPerformed
        // TODO add your handling code here:
        var_eqF.setText(""+(Integer.parseInt(var_eqF.getText())+100));
    }//GEN-LAST:event_esp_brujitaActionPerformed

    private void RecuperarEqVisitante(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esp_hierroActionPerformed
        // TODO add your handling code here:
        var_visita.setText(""+(Integer.parseInt(var_visita.getText())+100));
    }//GEN-LAST:event_esp_hierroActionPerformed
    
//  EN CASO DE DERROTA...
    public void msjEquipoHielo(){
        JOptionPane.showMessageDialog(var_visita, "El equipo hielo ha perdido");
        dispose();
        Menu abrir = new Menu();
        abrir.setVisible(true);
    }
    
    public void msjEquipoFuego(){
        JOptionPane.showMessageDialog(var_eqF,"El equipo fuego ha perdido");
        dispose();
        Menu abrir = new Menu();
        abrir.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArenaFuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArenaFuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArenaFuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArenaFuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArenaFuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atak_EqFuego;
    private javax.swing.JButton atacar_Hierro;
    private javax.swing.JButton esp_brujita;
    private javax.swing.JButton esp_hierro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTextField var_eqF;
    private javax.swing.JTextField var_visita;
    // End of variables declaration//GEN-END:variables
}
